name: Python GitHub Actions Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: read
  security-events: write

jobs:
  ci-pipeline-job:
    uses: aabhinnavkvd/reusable_pipelines/.github/workflows/ci-pipeline.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}