name: My Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Before Checkout
        run: ls -la
      - name: Code Checkout
        uses: actions/checkout@v6.0.0
      - name: list files
        run: ls -la