name: self-hosted-runner-workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: arc-runner-scaleset
    steps:
      - name: Display system information
        run: |
          echo "Running on a self-hosted runner!"
          echo "Operating System: $(uname -a)"
          echo "CPU Architecture: $(uname -m)"
          echo "Available Memory: $(free -h)"
          echo "Runner Name: ${{ runner.name }}"
          sleep 30

  job2:
    runs-on: arc-runner-scaleset
    steps:
     - name: Display system information
       run: |
         echo "Running on a self-hosted runner!"
         echo "Operating System: $(uname -a)"
         echo "CPU Architecture: $(uname -m)"
         echo "Available Memory: $(free -h)"
         echo "Runner Name: ${{ runner.name }}"
         sleep 30

  job3:
    runs-on: arc-runner-scaleset
    steps:
     - name: Display system information
       run: |
         echo "Running on a self-hosted runner!"
         echo "Operating System: $(uname -a)"
         echo "CPU Architecture: $(uname -m)"
         echo "Available Memory: $(free -h)"
         echo "Runner Name: ${{ runner.name }}"
         sleep 30

  job4:
    name: Python Setup
    runs-on: arc-runner-scaleset
    steps:
      - name: Python Setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

  job5:
    name: Node.js Setup
    runs-on: arc-runner-scaleset
    steps:
      - name: Node.js Setup
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          npm install axios

  job6:
    name: Java Setup
    runs-on: arc-runner-scaleset
    steps:
      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java Installation
        run: |
          echo "Running on a self-hosted runner!"
          echo "Operating System: $(uname -a)"
          echo "CPU Architecture: $(uname -m)"
          echo "Available Memory: $(free -h)"
          echo "Runner Name: ${{ runner.name }}"
          java -version
    
  job7:
    name: Docker Setup
    needs: [job4, job5, job6]
    runs-on: arc-runner-scaleset
    steps:
      - name: Docker Setup
        uses: docker/setup-buildx-action@v6

  job8:
    runs-on: arc-runner-scaleset
    steps:
      - name: Display system information
        run: |
          echo "Running on a self-hosted runner!"
          echo "Operating System: $(uname -a)"
          echo "CPU Architecture: $(uname -m)"
          echo "Available Memory: $(free -h)"
          echo "Runner Name: ${{ runner.name }}"
          sleep 30

  job9:
    runs-on: arc-runner-scaleset
    steps:
      - name: Display system information
        run: |
          echo "Running on a self-hosted runner!"
          echo "Operating System: $(uname -a)"
          echo "CPU Architecture: $(uname -m)"
          echo "Available Memory: $(free -h)"
          echo "Runner Name: ${{ runner.name }}"
          sleep 30
  
  job10:
    runs-on: arc-runner-scaleset
    needs: [job8, job9]
    steps:
      - name: Display system information
        run: |
          echo "Running on a self-hosted runner!"
          echo "Operating System: $(uname -a)"
  
  # python-job:
  #   runs-on: github-actions-scaleset-demo
  #   steps:
  #     - name: Set up Python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version: '3.x'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install requests
  #     - name: Run a Python script
  #       run: |
  #         echo "Running a Python script on a self-hosted runner!"
  #         python -c "import requests; print(requests.__version__)"
  
  # nodejs-job:
  #   runs-on: github-actions-scaleset-demo
  #   steps:
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: '24'
  #     - name: Install dependencies
  #       run: |
  #         npm install axios
  #     - name: Run a Node.js script
  #       run: |
  #         echo "Running a Node.js script on a self-hosted runner!"
  #         node -e "const axios = require('axios'); console.log(axios.VERSION);"
  
  