name: self-hosted-runner-workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: minikube-arc
    steps:
      - name: Display system information
        run: |
          echo "Running on a self-hosted runner!"
          echo "Operating System: $(uname -a)"
          echo "CPU Architecture: $(uname -m)"
          echo "Available Memory: $(free -h)"
          echo "Runner Name: ${{ runner.name }}"
          sudo apt-get update && sudo apt-get install -y python3
          python3 --version
          sleep 30

  job2:
    runs-on: minikube-arc
    steps:
     - name: Display system information
       run: |
         echo "Running on a self-hosted runner!"
         echo "Operating System: $(uname -a)"
         echo "CPU Architecture: $(uname -m)"
         echo "Available Memory: $(free -h)"
         echo "Runner Name: ${{ runner.name }}"
         sudo apt-get update && sudo apt-get install -y nodejs npm
         node --version
         npm --version
         sleep 30
