name: self-hosted-runner-workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: github-actions-scaleset-demo
    steps:
      - name: Display system information
        run: |
          echo "Running on a self-hosted runner!"
          echo "Operating System: $(uname -a)"
          echo "CPU Architecture: $(uname -m)"
          echo "Available Memory: $(free -h)"
          echo "Runner Name: ${{ runner.name }}"
          sleep 90

  job2:
    runs-on: github-actions-scaleset-demo
    steps:
     - name: Display system information
       run: |
         echo "Running on a self-hosted runner!"
         echo "Operating System: $(uname -a)"
         echo "CPU Architecture: $(uname -m)"
         echo "Available Memory: $(free -h)"
         echo "Runner Name: ${{ runner.name }}"
         sleep 90
